### ISSUE TITLE
Not able to set-up the project at my end

### ISSUE THREAD

**Issue by syedjawadakhtar** [husainhz7/AUV-FinalYear-Unity#1]
1. Warning pop up box after launching the project:
<img width="365" alt="error" src="https://user-images.githubusercontent.com/22319639/81824829-871efa80-9553-11ea-8fa9-3826e57da3c7.PNG">

2. When spawning the robot other items aren't visible. Also a warning message is seen at the bottom
<img width="658" alt="error1" src="https://user-images.githubusercontent.com/22319639/81824832-88e8be00-9553-11ea-8fce-6c49f734640e.PNG">

**Comment by syedjawadakhtar** [comment]
After installing the same version of Unity (2018.4.14f1 64-bit) the error persists.

**Comment by husain-zaidi** [comment]
you have to clone the original ml-agents repo:
https://github.com/Unity-Technologies/ml-agents/tree/0.15.1 and install the
unity package manually. Then try opening the project. Note the ml-agents
version and follow the steps from this specific repo only

**Comment by syedjawadakhtar** [comment]
I was able to press the play button in the arena, without any set-up errors, after the following:

1. Installing the correct version (v0.15.1) of `ml-agents` - from https://github.com/Unity-Technologies/ml-agents/releases/tag/0.15.1

2. Importing manually the packages following this link: https://docs.unity3d.com/Manual/upm-ui-local.html

3. Deleting the extra `Examples` and `Standard Assets` folder as it was throwing a lot of errors.

4. Removing the error related to `UnityShim` following this issue: https://github.com/github-for-unity/Unity/issues/1030
